name: quality

on:
  push:
    branches: [main]
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
        - name: Checkout
          uses: actions/checkout@v4
        - name: Setup Biome
          uses: biomejs/setup-biome@v2
          with:
            version: 2.0.0
        - name: Run Biome
          run: biome ci .
  doctor:
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v4
        - uses: oven-sh/setup-bun@v2
        - run: bun add -g expo-doctor
        - run: bun run expo-doctor
